---
title: "HW6"
author: "Ou Sha"
date: "2023-12-02"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(purrr)
library(MASS)
library(modelr)
```

# Problem 1
```{r}
# import data
homi <- read.csv("./data/homicide-data.csv")
```

```{r, warning=FALSE}
# clean data 
homi <- homi|>
  # create city_state variable
  mutate(city_state = str_c(city, state, sep = ", "))|>
  # create binary variable
  mutate(resolved = case_when(disposition == "Closed without arrest" ~ 0,
                          disposition == "Open/No arrest" ~0,
                          disposition == "Closed by arrest" ~ 1))|>
  # omit cities
  filter(!(city_state %in% c("Tulsa, AL", "Dallas, TX", 
                             "Phoenix, AZ", "Kansas City, MO")))|> 
  # limit races
  filter(victim_race %in% c("White", "Black"))|>
  # make age numeric
  mutate(victim_age = as.numeric(victim_age))|>
  dplyr::select(-city, - state, -disposition)
```

```{r}
# use the glm function to fit a logistic regression 
md_glm <- homi|> 
  filter(city_state == "Baltimore, MD")|> 
  dplyr::select(city_state, resolved, victim_age, victim_sex, victim_race)|>
  glm(resolved ~ victim_age + victim_race + victim_sex, data = _, family = binomial())
# save the output as an R object
save(md_glm, file = "baltimore_glm.RData")
md_glm|>
  # apply the broom::tidy to this object
  broom::tidy()|> 
  filter(term == "victim_sexMale")|> 
  mutate(OR = exp(estimate),
         OR_upper = exp(estimate + 1.96 * std.error),
         OR_lower = exp(estimate - 1.96 * std.error))|>
  dplyr::select(estimate, OR, OR_lower, OR_upper) |>
  knitr::kable(digits = 3)
```

```{r}
# run glm for each city
all_glm <- homi|>
  nest(city = -city_state) |> 
  mutate(log_re = map(city, \(x) glm(resolved ~ victim_age + victim_sex + victim_race, 
                             family = binomial(), data = x)),
         tidy= map(log_re, broom::tidy))|> 
  unnest(tidy)|>
  filter(term == "victim_sexMale")|> 
  mutate(OR = exp(estimate),
         OR_upper = exp(estimate + 1.96 * std.error),
         OR_lower = exp(estimate - 1.96 * std.error))|>
  dplyr::select(city_state, estimate, OR, OR_lower, OR_upper)
all_glm|>
  knitr::kable(digits = 3)
# create plot 
all_glm|>
  # Organize cities according to estimated OR
  ggplot(aes(x = OR, y = fct_reorder(city_state,OR))) + 
  geom_point() + 
  geom_errorbar(aes(xmin = OR_lower, xmax = OR_upper))+
  labs(x = "odds ratio", y = "cities", title = "Estimated ORs and CIs for each city")
```

Based on the plot, New York, NY has the smallest estimated odds ratio and Albuquerque, NM has the largest estimated odds ratio with a larger CI.

